// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using System;
using Indigo.Server.Data;

namespace Indigo.Server.Migrations
{
    [DbContext(typeof(IndigoContext))]
    internal class IndigoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Indigo.Core.Page", b =>
                {
                    b.Property<int>("PageId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("LastEdited");

                    b.Property<string>("Message");

                    b.Property<string>("Name");

                    b.HasKey("PageId");

                    b.ToTable("Pages");
                });
#pragma warning restore 612, 618
        }
    }
}
